name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      # Debug: Ver qué archivos hay en public antes de copiar
      - name: List public directory
        run: |
          echo "=== Public directory contents ==="
          ls -la public/ || echo "No public directory"
          echo "=== Sorpresa subdirectory ==="
          ls -la public/sorpresa/ || echo "No sorpresa subdirectory"
      
      # Copiar manualmente los archivos de public
      - name: Copy public assets  
        run: |
          if [ -d "public" ]; then
            # Copiar el contenido de public/sorpresa directamente a out/
            cp -r public/sorpresa/* out/
            echo "Files copied from public/sorpresa/ to out/"
          else
            echo "No public directory found"
          fi
      
      # Debug: Ver qué hay en out después de copiar
      - name: List out directory after copy
        run: |
          echo "=== Out directory contents ==="
          ls -la out/ || echo "No out directory"
          echo "=== Out/sorpresa subdirectory ==="
          ls -la out/sorpresa/ || echo "No sorpresa in out"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4